on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: mm-simple_version

      - uses: actions/checkout@v2

      # avoids bundle problems
      - name: remove Gemfile.lock
        run: |
          rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: bundle
        run: |
          bundle config unset --local deployment
          bundle

      - name: publish gem
        if: ${{ steps.release.outputs.release_created }}
        uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
