name: release
"on":
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.4.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v5
      - name: remove Gemfile.lock
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          rm Gemfile.lock
      - name: install ruby
        if: "${{ steps.release.outputs.release_created }}"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: bundle
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          bundle config unset --local deployment
          bundle
      - name: publish gem
        if: "${{ steps.release.outputs.release_created }}"
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: "${{secrets.RUBYGEMS_API_KEY}}"
          github_token: "${{secrets.GITHUB_TOKEN}}"
